#!/bin/sh

if [ -n "$DEBUG" ]; then
    set -x
fi

# Copy and overwrite default resources if it does not exist
echo "Copying default resources..."
cp -r /opt/cfx-server-data/* /config/resources

# Remove .gitkeep from resources in case it is mounted
if [ ! -e "/config/resources/.gitkeep" ]; then
    rm -f /config/resources/.gitkeep
fi

# Copy default config if it does not exist
if [ ! -e "/root/server.cfg" ]; then
    echo "Creating default config..."
    cp -r /opt/cfx-server-data/server.cfg /root/server.cfg
fi

# Prepare config with ENV values
cp /root/server.cfg /config/server.cfg
sed -i "s/{RCON_PASSWORD}/${RCON_PASSWORD}/g" /config/server.cfg
sed -i "s/{STEAM_API_KEY}/${STEAM_API_KEY}/g" /config/server.cfg

if [ -z "$NO_ONESYNC" ]; then
    ONESYNC_ARGS="+set onesync on +set onesync_population true"
fi

if [ -z "${NO_DEFAULT_CONFIG}" ]; then
    CONFIG_ARGS="$CONFIG_ARGS $ONESYNC_ARGS +exec /config/server.cfg"
fi

# English is hard
if [ -z "${NO_LICENSE_KEY}" ]; then
    if [ -z "${LICENSE_KEY}" ] && [ -n "${LICENCE_KEY}" ]; then
        LICENSE_KEY="${LICENCE_KEY}"
    fi

    if [ -z "${LICENSE_KEY}" ]; then
        echo "License key not found in environment, please create one at https://keymaster.fivem.net!"
        exit 1
    fi

    CONFIG_ARGS="$CONFIG_ARGS +set sv_licenseKey ${LICENSE_KEY}"
fi

echo "Server config args \"${CONFIG_ARGS}\""

exec /opt/cfx-server/ld-musl-x86_64.so.1 \
    --library-path "/usr/lib/v8/:/lib/:/usr/lib/" \
    -- \
    /opt/cfx-server/FXServer \
        +set citizen_dir /opt/cfx-server/citizen/ \
        $CONFIG_ARGS \
        $*
